#!/usr/bin/env python3

import sys, os
sys.path.insert(0,os.path.join(os.path.dirname(__file__), '..'))

import argparse
import budgetless

parser = argparse.ArgumentParser(description='Use budgetless to run maintainance tasks on your budget database.')
parser.add_argument('database', type=str, help='The database to use.')

subparsers = parser.add_subparsers(title='actions', description='The action to be performed by budgetless.', dest='action')

parser_init = subparsers.add_parser('init')
parser_init.add_argument('conf_file', help="The file storing init configuration.")

parser_sync = subparsers.add_parser('sync')

parser_run = subparsers.add_parser('run')
parser_run.add_argument('--debug', dest='debug', action='store_const', const=True, default=False)

parser_deploy = subparsers.add_parser('deploy')
parser_deploy.add_argument('--debug', dest='debug', action='store_const', const=True, default=False)

args = parser.parse_args()

b = budgetless.Budget(args.database)

if args.action == 'init':
	b.initialise(filename=args.conf_file)

if args.action == 'sync':
	b.sync()

if args.action == 'run':
	b.wsgi_app.run(debug=args.debug)

if args.action == 'deploy':
	b.wsgi_app.run(host='0.0.0.0', debug=args.debug)
